blank_issues_enabled: false
contact_links:
  - name: ğŸ“– æ–‡ä»¶
    url: https://ng-alain.com
    about: æŸ¥é–± ng-alain å®˜æ–¹æ–‡ä»¶
  - name: ğŸ’¬ Discussions
    url: https://github.com/7Spade/gighub-master/discussions
    about: åœ¨ Discussions ä¸­æå•æˆ–è¨è«–
  - name: ğŸ” Stack Overflow
    url: https://stackoverflow.com/questions/tagged/ng-alain
    about: æœå°‹æˆ–æå•æŠ€è¡“å•é¡Œ
